@startuml "test-uml"
skinparam backgroundcolor Ivory/Azure

"index" - "summary-with-image"
"404" - "page-header"
"single" - "page-header"
"summary-with-image" - "func/GetFeaturedImage"
"single" - "social-share"
"single" - "tags"
"single" - "commento"
"single" - "menu-contextual"
"list" - "summary"
"terms" - "summary"
"taxonomy" - "summary"
"baseof" - "site-favicon"
"baseof" - "head-additions"
"baseof" - "site-header"
"baseof" - "site-footer"
"baseof" - "site-scripts"
"site-header" - "site-navigation"
"site-footer" - "social-follow"
"social-share" - "size"
"site-navigation" - "i18nlist"
"site-navigation" - "social-follow"
"social-follow" - "size"
"social-follow" - "new-window-icon"
"page-header" - "func/GetFeaturedImage"
"page-header" - "site-navigation"
"new-window-icon" - "size"

@enduml
